version: "3.9"

services:
  redis:
    image: redis:7
    container_name: medical-redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: medical-api
    command: >
      python -m uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    depends_on:
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    container_name: medical-worker
    command: >
      celery -A celery_worker.celery_app
      worker --loglevel=info --pool=solo
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    depends_on:
      - redis

  streamlit:
    build: .
    container_name: medical-ui
    command: >
      streamlit run frontend/streamlit_app.py
      --server.port=8501
      --server.address=0.0.0.0
    env_file:
      - .env
    environment:
      API_BASE_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"
